### ISSUE TITLE
Sockets issue

### ISSUE THREAD

**Issue by advaita-krishna-das** [advaita-krishna-das/gem#96]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 405, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 243, in _handler
    *args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 626, in _handle_event
    ret = handler(*args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/akd/Develop/gem/gem/web/blueprints/session/session.py", line 23, in on_join_message
    return controller.join(request.sid, current_user, data)
  File "/Users/akd/Develop/gem/gem/web/blueprints/session/controller.py", line 54, in join
    disconnect()
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 844, in disconnect
    namespace=flask.request.namespace)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 333, in disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 243, in _handler
    *args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 626, in _handle_event
    ret = handler(*args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/akd/Develop/gem/gem/web/blueprints/session/session.py", line 59, in on_disconnect
    return controller.disconnect(request.sid)
  File "/Users/akd/Develop/gem/gem/web/blueprints/session/controller.py", line 113, in disconnect
    self.__sockets.disconnect(socket_id)
  File "/Users/akd/Develop/gem/gem/web/blueprints/session/socket_sessions.py", line 30, in disconnect
    self.__by_room[socket_id].users.leave(socket_id)
KeyError: 'a84dca78245b443bbe5a2e890abb4803'

**Comment by advaita-krishna-das** [comment]
Done
